version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: image_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: image_db
      DB_USER: user
      DB_PASS: password
      SEARCH_QUERY: "cute kittens"
      MAX_IMAGES: "5"
    ports:
      - "5000:5000"

volumes:
  db_data:
